const mongoose = require('mongoose')
const Recipe = require('../models/Recipe')
const User = require('../models/User')
const recipeData = require('./data/recipeData')
const userData = require('./data/userData')
const { dbURI } = require('../config/environment')

mongoose.connect(dbURI, { useNewUrlParser: true })
  .then(() => mongoose.connection.db.dropDatabase())
  .then(() => Recipe.create(recipeData))
  .then(() => User.create(userData))
  .then(() => console.log('Successfully seeded!'))
  .catch((err) => console.log(err))
  .finally(() => mongoose.connection.close())
